image: Visual Studio 2017
branches:
  only:
  - master
  - develop
install:
  - cinst gitversion.portable -y
before_build:
  - nuget restore
  - ps: $env:VERSION=$(gitversion /showvariable NuGetVersionV2)
build_script:
  - ps: dotnet restore
  - ps: cd src/AsyncEvent; dotnet setversion $env:VERSION; cd ../..
  - ps: dotnet build
  - ps: dotnet pack --include-source --include-symbols -c Release -o out/
test_script:
  - ps: cd test/AsyncEvent.Tests; dotnet test
artifacts:
  path: src/AsyncEvent/out/*.nupkg
  name: NuGet packages
deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: u6wyCWr7El0iC167KlsklNSFw5xXBq3WPgegevdthWJfGRHQlCrcxc7AikJh+ePS
  artifact: NuGet packages
  on:
    branch: master